schemaVersion: '2.0'

machine:
  baseImage: docker.apple.com/base-images/ubi9/ubi-builder:latest

pipelines:
  - name: build-risingwave-image
    branchName: main
    machine:
      baseImage: docker.apple.com/base-images/ubi9/ubi-builder:latest
      env:
        CARGO_PROFILE: "${BUILD_PARAM_cargo_profile}"
    checkout:
      fetchTags: true
    build:
      template: freestyle:v4:publish
      buildParameters:
        - parameter: tag
          description: tag to be built
        - parameter: cargo_profile
          description: cargo profile to use
      steps:
        - git checkout ${BUILD_PARAM_tag}
    package:
      dockerfile:
      - dockerfilePath: docker/Dockerfile
        perApplication: false
        version: "0.0.${RIO_BUILD_NUMBER}"
        publish:
        - repo: docker.apple.com/hitesh_lnu/risingwave
    trigger:
      gitPush: false
